"use client";

import Image from "next/image";
import { useState } from "react";
import type { ConsoleReadModel } from "@/components/demo-console/demo-console-types";

type CaseStoryConsoleProps = { miroEmbedUrl?: string; miroBoardUrl?: string; readModel: ConsoleReadModel; pollingState: "loading" | "ready" | "paused"; refreshedAt?: string; readFailure?: string; teamCalendarEmbedUrls?: { teamA?: string; teamB?: string } };
const lifecycleTitles = { new_lead: "New Lead", qualified: "Qualified", booked: "Booked", done: "Done", lost: "Lost" } as const;
const activityTitles: Record<string, string> = { lead_created: "Request received", date_proposed: "Date proposed", date_proposal_confirmed: "Requested date confirmed", quote_delivered: "Quote prepared", calendar_reserved_pending_trello: "Calendar reserved", trello_synced: "Trello updated", booking_confirmed: "Booking confirmed" };
const productAssets: Record<string, string> = { telegram: "/brand/integrations/telegram.svg", openai: "/brand/integrations/openai-icon.svg", google_calendar: "/brand/integrations/google-calendar.svg", trello: "/brand/integrations/trello.svg" };
const productLabels: Record<string, string> = { telegram: "Telegram", openai: "OpenAI", google_calendar: "Google Calendar", trello: "Trello" };

function ProductIcon({ id }: { id: string }) {
  const [failed, setFailed] = useState(false);
  const src = productAssets[id];
  if (!src || failed) return <span aria-label={`${productLabels[id] ?? "Integration"} icon unavailable`} className="grid h-5 min-w-5 place-items-center rounded border border-slate-300 bg-white px-1 text-[9px] font-bold text-slate-700">?</span>;
  return <Image alt={`${productLabels[id] ?? "Integration"} icon`} className="h-5 w-5 shrink-0" height={20} onError={() => setFailed(true)} src={src} unoptimized width={20} />;
}
function ExternalLink({ href, label }: { href?: string; label: string }) { return href ? <a className="inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-bold text-slate-700 transition hover:bg-slate-50" href={href} rel="noreferrer" target="_blank">{label} ↗</a> : <span aria-disabled="true" className="inline-flex min-h-11 cursor-not-allowed items-center justify-center rounded-xl border border-slate-200 bg-slate-100 px-4 text-sm font-bold text-slate-400">{label} unavailable</span>; }

export function CaseStoryConsole({ miroEmbedUrl, miroBoardUrl, teamCalendarEmbedUrls, pollingState, readFailure, readModel, refreshedAt }: CaseStoryConsoleProps) {
  const [miroBlocked, setMiroBlocked] = useState(false);
  const lead = readModel.latestLead;
  const trelloColumns = (Object.keys(lifecycleTitles) as Array<keyof typeof lifecycleTitles>).map((lifecycle) => ({ title: lifecycleTitles[lifecycle], cards: readModel.trelloBoard.cards.filter((card) => card.lifecycle === lifecycle) }));
  const activity = readModel.latestLeadActivity.slice(-4);
  const status = readModel.currentStatusDetail || (lead ? lifecycleTitles[lead.lifecycle] : "No lead yet");
  const needsHuman = readModel.currentStatus === "human_needed";
  const directTrelloCardUrl = safeTrelloCardUrl(lead?.trelloCardUrl);
  const service = lead?.cleaningType ? `${lead.cleaningType === "deep" ? "Deep" : "Standard"} cleaning${lead.areaM2 ? ` · ${lead.areaM2} m²` : ""}` : "Service details are not available";
  const isConfirmedBooking = lead?.bookingConfirmed && Boolean(lead.bookedStart) && Boolean(lead.assignedTeam);
  const requestDate = lead?.preferredDate ? formatRequestedDate(lead.preferredDate) : "Not requested yet";
  const refreshCopy = refreshedAt ? `Updated ${formatTime(refreshedAt)}` : "Waiting for first update";

  return <main className="min-w-0 bg-slate-50 pb-16 pt-5 text-slate-900 md:ml-[var(--console-sidebar-width)] md:pt-8"><div className="mx-auto w-full max-w-7xl space-y-10 px-4 sm:px-6 md:space-y-12 lg:px-8">
    <section aria-labelledby="hero-title" className="rounded-3xl border border-teal-100 bg-gradient-to-br from-teal-50 via-white to-amber-50 px-6 py-8 shadow-sm sm:px-10">
      <div className="max-w-3xl"><h1 className="max-w-2xl text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl" id="hero-title">From a Telegram enquiry to booked cleaning — automatically.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-600">Our AI agent listens, qualifies, quotes, schedules and confirms — end to end.</p>
        <div aria-label="Core automated flow" className="mt-5 flex flex-wrap items-center gap-x-2 gap-y-3 text-sm font-bold text-slate-700"><ProductMark id="telegram" label="Telegram" /><span aria-hidden className="text-slate-400">→</span><ProductMark id="openai" label="AI assistant" /><span aria-hidden className="text-slate-400">→</span><ProductMark id="google_calendar" label="Calendar" /><span aria-hidden className="text-slate-400">→</span><ProductMark id="trello" label="Trello" /></div>
        <div className="mt-6 flex flex-wrap gap-3"><a className="inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-4 text-sm font-bold text-white shadow-sm transition hover:bg-teal-800" href="https://t.me/sherlock_cleaning_bot" rel="noreferrer" target="_blank">Write to the bot ↗</a><a className="inline-flex min-h-11 items-center rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 transition hover:bg-slate-50" href="#latest-lead">See the latest flow ↓</a></div>
      </div>
    </section>

    <section aria-labelledby="latest-lead-title" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" id="latest-lead">
      <div className="grid lg:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]"><div className="p-5 sm:p-7"><h2 className="text-lg font-semibold tracking-tight text-slate-950" id="latest-lead-title">Real-time information about the latest lead</h2><p className="mt-1 text-sm text-slate-600">This panel refreshes as the most recent customer request moves through the application.</p><div className="mt-5 flex items-center gap-2 text-sm font-bold text-teal-900"><span aria-hidden className={`h-2.5 w-2.5 rounded-full ${needsHuman ? "bg-amber-500" : "bg-emerald-500"}`} />{needsHuman ? "Human Needed" : status}</div><dl className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Fact label="Request" value="One-time apartment clean" /><Fact label="Service" value={service} /><Fact label={isConfirmedBooking ? "Booking" : lead?.preferredDate ? "Requested date" : "Booking"} value={isConfirmedBooking ? `${formatDateTime(lead?.bookedStart ?? "")} · ${lead?.assignedTeam === "team_a" ? "Team A" : "Team B"}` : requestDate} /><Fact label="Quote" value={lead?.quotedPriceRsd ? `${lead.quotedPriceRsd.toLocaleString("en-US")} RSD` : "Not quoted yet"} /></dl>{needsHuman && <div className="mt-5">{directTrelloCardUrl ? <a className="text-sm font-bold text-amber-800 underline underline-offset-4" href={directTrelloCardUrl} rel="noreferrer" target="_blank">Open this Trello card ↗</a> : <p className="text-sm font-medium text-amber-800">Human Needed is recorded. Use the Trello board below.</p>}</div>}</div>
        <aside aria-label="Integration status" className="border-t border-slate-200 bg-slate-50 p-5 lg:border-l lg:border-t-0 sm:p-7"><p className="text-sm font-bold text-slate-700">Integration readiness</p><div className="mt-3 grid gap-2">{readModel.integrations.map((integration) => <div className="flex items-center gap-2" key={integration.id}><ProductIcon id={integration.id} /><span className={`h-2 w-2 rounded-full ${integration.readiness === "ready" ? "bg-emerald-500" : integration.readiness === "attention" ? "bg-amber-500" : "bg-slate-400"}`} /><span className="text-sm font-semibold text-slate-700">{integration.label}</span><span className="ml-auto text-xs text-slate-500">{integration.detail}</span></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">{readModel.snapshotKind === "application_snapshot" ? "Application snapshot. Providers are not live checked. " : ""}{pollingState === "paused" ? `Updates paused. ${readFailure ?? ""}` : refreshCopy} Times shown in Europe/Belgrade.</p></aside>
      </div>
      <ol aria-label="Latest lead activity" className="grid gap-3 border-t border-slate-200 p-5 sm:grid-cols-2 lg:grid-cols-4 sm:p-7">{activity.length ? activity.map((item) => <li className="min-w-0 border-l-2 border-teal-600 pl-3" key={`${item.eventType}-${item.occurredAt}`}><p className="text-sm font-bold text-slate-800">{activityTitles[item.eventType] ?? "Latest lead update"}</p><time className="mt-1 block text-xs font-medium text-slate-500">{formatTime(item.occurredAt)}</time></li>) : <li className="border-l-2 border-slate-300 pl-3"><p className="text-sm font-bold text-slate-700">No confirmed activity yet</p><p className="mt-1 text-xs text-slate-500">The next lead update will appear here.</p></li>}</ol>
    </section>

    <section aria-labelledby="trello-title"><div className="mb-4 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-tight text-slate-950" id="trello-title">Trello remains where work is handled.</h2><p className="mt-1 text-sm text-slate-600">A live, read-only board view. Manual moves and cards appear here without changing the application.</p>{readModel.trelloBoard.kind === "projection" && <p className="mt-1 text-xs font-medium text-slate-500">{readModel.trelloBoard.freshness === "stale" ? "Showing the last successful Trello refresh." : "Trello refreshed"}{readModel.trelloBoard.observedAt ? ` ${formatTime(readModel.trelloBoard.observedAt)}.` : ""}</p>}</div><ExternalLink href={readModel.trelloBoard.boardUrl} label="Open in Trello" /></div><div className="overflow-x-auto rounded-2xl bg-teal-800 p-4 shadow-sm"><div aria-label="Read-only Trello lifecycle projection" className="flex w-fit min-w-full gap-3">{readModel.trelloBoard.kind === "projection" ? trelloColumns.map((column) => <article className="w-64 shrink-0 rounded-xl bg-teal-50 p-3" key={column.title}><h3 className="flex items-center justify-between text-sm font-bold text-teal-950">{column.title}<span className="rounded-full bg-teal-100 px-2 py-0.5 text-xs">{column.cards.length}</span></h3><div className="mt-3 grid gap-3">{column.cards.map((card, index) => <article className="rounded-lg bg-white p-3 shadow-sm" key={`${column.title}-${card.cardUrl ?? card.title}-${index}`}>{card.humanNeeded && <span className="mb-2 block h-1.5 w-9 rounded-full bg-amber-400" />}<p className="text-sm font-bold leading-5 text-slate-800">{card.title}</p>{safeTrelloCardUrl(card.cardUrl) && <a className="mt-2 inline-block text-xs font-bold text-teal-700 underline underline-offset-2" href={safeTrelloCardUrl(card.cardUrl)} rel="noreferrer" target="_blank">Open card ↗</a>}</article>)}</div></article>) : <p className="p-5 text-sm font-medium text-teal-50">{readModel.trelloBoard.kind === "not_configured" ? "Trello is not configured for this environment." : "The live Trello board could not be read right now."}</p>}</div></div></section>

    <section aria-labelledby="calendar-title"><div className="mb-4"><h2 className="text-2xl font-semibold tracking-tight text-slate-950" id="calendar-title">Team availability</h2><p className="mt-1 text-sm text-slate-600">Application-owned booking evidence is shown safely. Configured public calendars remain separate read-only views.</p></div><div className="grid gap-6"><CalendarPanel label="Team A" lead={lead} team="team_a" url={teamCalendarEmbedUrls?.teamA} /><CalendarPanel label="Team B" lead={lead} team="team_b" url={teamCalendarEmbedUrls?.teamB} /></div></section>

    <section aria-labelledby="miro-title"><div className="mb-4 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-tight text-slate-950" id="miro-title">The decisions behind the flow.</h2><p className="mt-1 text-sm text-slate-600">The project Miro board is view-only here, with a direct fallback when embedding is unavailable.</p></div><ExternalLink href={miroBoardUrl ?? miroEmbedUrl} label="Open Miro" /></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="relative aspect-video w-full min-h-[220px]">{miroEmbedUrl && !miroBlocked ? <iframe allowFullScreen className="absolute inset-0 block h-full w-full border-0" onError={() => setMiroBlocked(true)} src={miroEmbedUrl} title="Sherlock Cleaning project Miro board" /> : <div className="grid h-full place-items-center bg-slate-50 p-6 text-center"><div><p className="font-bold text-slate-800">Miro view is unavailable in this browser.</p><p className="mt-2 text-sm text-slate-600">Use the direct project link above to open the board.</p></div></div>}</div></div></section>
  </div></main>;
}

function ProductMark({ id, label }: { id: string; label: string }) { return <span className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 shadow-sm"><ProductIcon id={id} /><span>{label}</span></span>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm font-bold leading-5 text-slate-800">{value}</dd></div>; }
function CalendarPanel({ label, lead, team, url }: { label: string; lead: ConsoleReadModel["latestLead"]; team: "team_a" | "team_b"; url?: string }) { const bookedHere = lead?.bookingConfirmed && lead.assignedTeam === team && Boolean(lead.bookedStart); return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><h3 className="font-bold text-slate-900">{label}</h3><span className="text-sm font-medium text-slate-600">{bookedHere ? `Occupied ${formatDateTime(lead?.bookedStart ?? "")}` : "No confirmed booking in this snapshot"}</span></div>{url ? <iframe className="block min-h-[520px] w-full border-0" loading="lazy" src={url} title={`${label} public calendar`} /> : <div className="p-5 text-sm leading-6 text-slate-600">A public calendar view is not configured. This safe application projection does not expose event details.</div>}</article>; }
function formatTime(value: string) { return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Belgrade" }).format(new Date(value)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Belgrade" }).format(new Date(value)); }
function formatRequestedDate(value: string) { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "Europe/Belgrade" }).format(new Date(`${value}T12:00:00.000Z`)); }
function safeTrelloCardUrl(value: string | undefined) { if (!value) return undefined; try { const url = new URL(value); return url.protocol === "https:" && ["trello.com", "www.trello.com"].includes(url.hostname) && /^\/c\/[A-Za-z0-9_-]{1,64}(?:\/[^/?#]+)?\/?$/.test(url.pathname) && !url.username && !url.password && !url.search && !url.hash ? url.toString() : undefined; } catch { return undefined; } }
